
/*------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------*/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MVCLearning
{
    public class ErrorMessages
    {
        public static string EmailInvalid
        {
            get
            {
                return "Email is not valid";
            }
        }

        public static string IDCardNumberRequired
        {
            get
            {
                return "Card number is not valid";
            }
        }
         
    }
}