
/*------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------*/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MVCLearning.Translations.ErrorMessages
{
	public class ErrorMessages
	{
		public static string EmailInvalid
		{
			get 
			{
				return "Email is not valid";
			}
		}
		public static string IDCardNumberRequired
		{
			get 
			{
				return "Card number is not valid";
			}
		}
		public static string IDCardValidityRequired
		{
			get 
			{
				return "ID Card validity is required";
			}
		}
		public static string InvalidIDCardValidity
		{
			get 
			{
				return "Invalid ID card validity";
			}
		}
		public static string InBelgiumSinceRequired
		{
			get 
			{
				return "In belgium since is required";
			}
		}
		public static string InBelgiumSinceValid
		{
			get 
			{
				return "InBelgiumSince should be less than system date";
			}
		}
		public static string LanguageRequired
		{
			get 
			{
				return "Language is required";
			}
		}
		public static string NationalityRequired
		{
			get 
			{
				return "nationality is required";
			}
		}
	}
}